"""FORGE crew (v0.3 milestone 13b). A fake brain plays the roles; the REAL static review and sandbox judge."""

import json
import re
import time

import pytest

from core import forge_crew as fc
from core.forge_engine import Forge

MOON = '''import json
from datetime import datetime, timezone

NEW = datetime(2000, 1, 6, 18, 14, tzinfo=timezone.utc)
SYN = 29.530588853
NAMES = ["new moon", "waxing crescent", "first quarter", "waxing gibbous", "full moon",
         "waning gibbous", "last quarter", "waning crescent"]


def moon_phase(date: str = "", **_):
    try:
        d = datetime.fromisoformat(date).replace(tzinfo=timezone.utc) if date else datetime.now(timezone.utc)
    except ValueError:
        return {"result": json.dumps({"error": "bad date"}), "say": "I need a date like 2026-10-01, sir."}
    age = ((d - NEW).total_seconds() / 86400) % SYN
    name = NAMES[int((age / SYN) * 8 + 0.5) % 8]
    return {"result": json.dumps({"phase": name, "age_days": round(age, 1)}), "say": f"It's a {name}, sir."}
'''

TESTS = '''import json
import tools


def test_new_moon_at_the_epoch():
    out = tools.moon_phase(date="2000-01-06T18:14:00")
    assert json.loads(out["result"])["phase"] == "new moon" and out["say"]


def test_bad_date_is_an_error_not_a_crash():
    out = tools.moon_phase(date="not a date")
    assert "error" in json.loads(out["result"])
'''

PLAN = {"feasible": True, "name": "moon_phase", "description": "Tells the moon phase for a date.",
        "summary_for_user": "It tells you the moon phase, offline.", "method": "offline formula",
        "network_hosts": [], "tools": [{"name": "moon_phase", "description": "The moon phase for a date (YYYY-MM-DD).",
                                        "params": {"date": "string"}, "changes_something": False,
                                        "trigger_words": ["moon", "phase", "lunar"]}],
        "test_cases": [{"tool": "moon_phase", "args": {"date": "2000-01-06T18:14:00"}, "expect": "new moon"}]}


class FakeBrain:
    def __init__(self, plan=PLAN, coder=None, tester=None, fixer=None, review=None, mode="local", delay=0.0):
        self.plan, self.mode, self.delay = plan, mode, delay
        self.coder = list(coder or [f"```python\n{MOON}```"])
        self.tester = tester or f"```python\n{TESTS}```"
        self.fixer = list(fixer or [])
        self.review = review or {"safe": True, "matches_request": True, "concerns": []}
        self.calls = []

    def pick(self, feature=None):
        return self.mode

    def code_json(self, system, messages, tool):
        role = re.match(r"ROLE: (\w+)", system).group(1)
        self.calls.append(role)
        return (self.plan if role == "planner" else self.review), 0.0, "fake"

    def code_text(self, system, messages):
        role = re.match(r"ROLE: (\w+)", system).group(1)
        self.calls.append(role)
        time.sleep(self.delay)
        if role == "coder":
            return self.coder.pop(0), 0.0, "fake"
        if role == "tester":
            return self.tester, 0.0, "fake"
        return self.fixer.pop(0), 0.0, "fake"


@pytest.fixture
def forge(tmp_path):
    f = Forge(skills_dir=tmp_path / "skills", brain=None)
    f._state = tmp_path / "proposals.json"
    return f


def build(forge, brain, request="tell me the moon phase", stages=None):
    return fc.Crew(brain, forge, progress=(stages.append if stages is not None else None)).build(request)


def test_the_moon_phase_builds_and_passes_its_independent_tests(forge):
    stages = []
    p = build(forge, FakeBrain(), stages=stages)
    assert p.status == "ready", p.reason
    assert p.tests_passed == 2 and p.tools == ["moon_phase"] and p.network_hosts == []
    assert stages == ["planning", "coding and writing tests", "reviewing"]
    tools_py = (forge.quarantine / "moon_phase" / "tools.py").read_text(encoding="utf-8")
    assert "generated by FORGE from the plan (not by a model)" in tools_py
    assert "trusted: false" in (forge.quarantine / "moon_phase" / "SKILL.md").read_text(encoding="utf-8")


def test_the_log_case_a_wrong_function_name_is_fixed_by_the_fixer(forge):
    wrong = "```python\n" + MOON.replace("def moon_phase(", "def moonphase(") + "```"
    brain = FakeBrain(coder=[wrong], fixer=[f"```python\n{MOON}```"])
    stages = []
    p = build(forge, brain, stages=stages)
    assert p.status == "ready", p.reason
    assert brain.calls == ["planner", "coder", "tester", "fixer", "reviewer"]
    assert "fixing, round 1 of 4" in stages


def test_a_failing_test_goes_back_with_the_real_error(forge):
    broken = "```python\n" + MOON.replace('NAMES[int((age / SYN) * 8 + 0.5) % 8]', '"full moon"') + "```"
    brain = FakeBrain(coder=[broken], fixer=[f"```python\n{MOON}```"])
    p = build(forge, brain)
    assert p.status == "ready"


def test_gives_up_honestly_after_the_last_round(forge):
    broken = "```python\ndef moonphase(**_):\n    return {}\n```"
    p = build(forge, FakeBrain(coder=[broken], fixer=[broken] * 4))
    assert p.status == "rejected" and "moon_phase is missing" in p.reason


def test_only_the_planner_can_say_cant_be_done(forge):
    p = build(forge, FakeBrain(plan={"feasible": False, "reason": "needs a paid API key"}))
    assert p.status == "infeasible" and p.reason == "needs a paid API key"


def test_the_reviewer_can_stop_an_unsafe_skill(forge):
    p = build(forge, FakeBrain(review={"safe": False, "matches_request": True, "concerns": ["sends data out"]}))
    assert p.status == "rejected" and "unsafe" in p.reason


def test_the_reviewer_can_stop_a_skill_that_misses_the_point(forge):
    p = build(forge, FakeBrain(review={"safe": True, "matches_request": False, "concerns": ["tells the sun"]}))
    assert p.status == "rejected" and "doesn't do what you asked" in p.reason


def test_the_static_review_still_blocks_bad_code(forge):
    evil = "```python\nimport subprocess\n" + MOON + "```"
    p = build(forge, FakeBrain(coder=[evil], fixer=[evil] * 4))
    assert p.status == "rejected" and "imports subprocess" in p.reason


def test_boilerplate_from_the_model_is_ignored():
    impl = MOON + '\nTOOLS = []\nGUARDS = {"x": 1}\n'
    out = fc.assemble(fc.normalize_plan(PLAN), impl)
    assert out.count("TOOLS = ") == 1 and '"moon_phase": moon_phase' in out
    assert json.dumps({"moon_phase": r"\b(moon|phase|lunar)\b"}) in out


def test_confirm_and_actions_come_from_the_plan():
    plan = fc.normalize_plan({**PLAN, "tools": [{"name": "delete_note", "description": "Delete a note.",
                                                  "params": {"title": "string"}, "changes_something": True,
                                                  "confirm": "delete the note {title}", "trigger_words": ["delete", "note"]}]})
    block = fc.contract_block(plan)
    assert 'ACTIONS = ["delete_note"]' in block and '"delete the note {title}"' in block


def test_code_blocks_are_found_with_or_without_a_language():
    assert fc.code_blocks("text\n```python\nx = 1\n```\nmore") == ["x = 1"]
    assert fc.code_blocks("```\ndef f():\n    pass\n```") == ["def f():\n    pass"]
    assert fc.code_blocks("def g():\n    return 1") == ["def g():\n    return 1"]


def test_with_claude_the_coder_and_tester_work_at_the_same_time(forge):
    t0 = time.monotonic()
    p = build(forge, FakeBrain(mode="cloud", delay=0.4))
    assert p.status == "ready" and time.monotonic() - t0 < 0.75          # 2 x 0.4 s, in parallel


def test_forge_uses_the_crew_in_production_and_reports_stages(tmp_path, monkeypatch):
    import core.forge_jobs as fj
    f = Forge(skills_dir=tmp_path / "skills", brain=FakeBrain())
    f._state = tmp_path / "proposals.json"
    assert f._use_crew()
    m = fj.JobManager(forge_factory=lambda: f, threaded=False)
    job = m.submit("tell me the moon phase")
    assert job.status == "done" and job.result_status == "ready" and job.stage == "reviewing"


def test_crew_can_be_switched_off(tmp_path, monkeypatch):
    import core.settings as st
    local = tmp_path / "settings.local.yaml"
    local.write_text("forge:\n  crew: false\n", encoding="utf-8")
    monkeypatch.setattr(st, "LOCAL_PATH", local)
    st.get_settings.cache_clear()
    assert not Forge(skills_dir=tmp_path / "s", brain=FakeBrain())._use_crew()


def test_brain_code_text_yields_like_the_json_path(monkeypatch):
    import httpx
    from core import activity
    from core.brain import Brain
    b = Brain(claude=None)
    monkeypatch.setattr(b, "pick", lambda *a, **k: "local")
    lines = [json.dumps({"message": {"content": "```python\nx = 1\n```"}, "done": False}),
             json.dumps({"message": {"content": ""}, "done": True})]
    b.http = httpx.Client(transport=httpx.MockTransport(lambda r: httpx.Response(200, text="\n".join(lines))))
    monkeypatch.setattr(activity, "wait_quiet", lambda *a, **k: None)
    text, cost, provider = b.code_text("ROLE: coder.", [{"role": "user", "content": "go"}])
    assert "x = 1" in text and cost == 0.0
